// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Full health check",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/admin/app-versions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "versioning"
                ],
                "summary": "List all platform version policies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_appversion_service.AppVersion"
                            }
                        }
                    }
                }
            }
        },
        "/v1/admin/app-versions/{platform}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "versioning"
                ],
                "summary": "Create or update version policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ios | android | web",
                        "name": "platform",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_appversion_service.AppVersion"
                        }
                    }
                }
            }
        },
        "/v1/admin/notifications/test-email": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin diagnostic endpoint — sends a minimal message through whichever mail transport is configured (SES or SMTP) and reports the raw result (including connection/auth errors), so email delivery can be debugged without creating a real user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Send a test email to verify MAIL_DRIVER configuration",
                "parameters": [
                    {
                        "description": "Recipient address",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_notification_dto.TestEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_notification_dto.TestEmailResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/v1/app-version/check": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "versioning"
                ],
                "summary": "Check if app version is current",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client version e.g. 2.4.1",
                        "name": "X-App-Version",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "ios | android | web",
                        "name": "X-App-Platform",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_appversion_service.VersionCheckResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/2fa/enable": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Enable two-factor authentication",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_auth_dto.Enable2FAResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/2fa/verify": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Verify and activate 2FA",
                "parameters": [
                    {
                        "description": "TOTP code",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_auth_dto.Verify2FARequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/v1/auth/apple/callback": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Apple Sign In callback",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_auth_dto.LoginResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/github": {
            "get": {
                "tags": [
                    "auth"
                ],
                "summary": "Redirect to GitHub OAuth",
                "responses": {
                    "302": {
                        "description": "Found"
                    }
                }
            }
        },
        "/v1/auth/github/callback": {
            "get": {
                "tags": [
                    "auth"
                ],
                "summary": "GitHub OAuth callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CSRF state",
                        "name": "state",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_auth_dto.LoginResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login with email \u0026 password",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_auth_dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_auth_dto.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/v1/auth/logout": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout (revoke current session)",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/v1/auth/logout-all": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout from all devices",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/auth/passkey/login/begin": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Begin usernameless passkey login",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/auth/passkey/login/finish": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Complete usernameless passkey login",
                "parameters": [
                    {
                        "description": "Assertion response",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_passkey_dto.FinishLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/auth/refresh": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh access token",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_auth_dto.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_auth_dto.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/v1/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new account",
                "parameters": [
                    {
                        "description": "Registration payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_auth_dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_auth_dto.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/v1/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get my profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_user_dto.UserResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update my profile",
                "parameters": [
                    {
                        "description": "Update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_user_dto.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_user_dto.UserResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/v1/me/mobiles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile"
                ],
                "summary": "List verified mobile numbers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_mobile_entity.UserMobile"
                            }
                        }
                    }
                }
            }
        },
        "/v1/me/mobiles/send-otp": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sends a 6-digit code via SMS or WhatsApp. channel: \"sms\" | \"whatsapp\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile"
                ],
                "summary": "Send OTP to a mobile number",
                "parameters": [
                    {
                        "description": "Phone number in E.164 format and channel",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "channel": {
                                    "type": "string"
                                },
                                "e164": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/me/mobiles/verify": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mobile"
                ],
                "summary": "Verify mobile OTP",
                "parameters": [
                    {
                        "description": "Phone number and 6-digit code",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "code": {
                                    "type": "string"
                                },
                                "e164": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/me/mobiles/{e164}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "mobile"
                ],
                "summary": "Remove a mobile number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "E.164 phone number",
                        "name": "e164",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/v1/me/mobiles/{e164}/primary": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "mobile"
                ],
                "summary": "Set primary mobile number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "E.164 phone number",
                        "name": "e164",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/me/passkeys": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "passkeys"
                ],
                "summary": "List my passkeys",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_passkey_dto.PasskeyResponse"
                            }
                        }
                    }
                }
            }
        },
        "/v1/me/passkeys/register/begin": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Pass ?attachment=platform for Touch ID / Face ID, cross-platform for hardware keys.",
                "tags": [
                    "passkeys"
                ],
                "summary": "Begin passkey / biometric registration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "platform | cross-platform",
                        "name": "attachment",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/me/passkeys/register/finish": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "passkeys"
                ],
                "summary": "Complete passkey / biometric registration",
                "parameters": [
                    {
                        "description": "Attestation response",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_passkey_dto.FinishRegistrationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_passkey_dto.PasskeyResponse"
                        }
                    }
                }
            }
        },
        "/v1/me/passkeys/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "passkeys"
                ],
                "summary": "Remove a passkey",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Passkey ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/v1/me/password": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Change my password",
                "parameters": [
                    {
                        "description": "Password payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_user_dto.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/v1/roles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Used to populate role-selection dropdowns (e.g. admin \"create user\" form)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roles"
                ],
                "summary": "List all roles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_role_dto.RoleResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/v1/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List users (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "perPage",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search term",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field",
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "asc | desc",
                        "name": "sortDir",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_user_dto.UserListResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create user (admin)",
                "parameters": [
                    {
                        "description": "User payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_user_dto.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_user_dto.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/v1/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by ID (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_user_dto.UserResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete user (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_user_dto.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_user_dto.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/v1/users/{id}/block": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Block a user (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Block reason",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_user_dto.BlockUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/v1/users/{id}/unblock": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "users"
                ],
                "summary": "Unblock a user (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_appversion_service.AppVersion": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "currentVersion": {
                    "description": "latest published, e.g. \"2.5.0\"",
                    "type": "string"
                },
                "forceUpdate": {
                    "description": "if true, block below minVersion",
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "minVersion": {
                    "description": "minimum allowed, e.g. \"2.0.0\"",
                    "type": "string"
                },
                "platform": {
                    "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_appversion_service.Platform"
                },
                "releaseNotes": {
                    "type": "string"
                },
                "storeUrl": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_appversion_service.Platform": {
            "type": "string",
            "enum": [
                "ios",
                "android",
                "web"
            ],
            "x-enum-varnames": [
                "PlatformIOS",
                "PlatformAndroid",
                "PlatformWeb"
            ]
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_appversion_service.UpdateStatus": {
            "type": "string",
            "enum": [
                "required",
                "available",
                "up_to_date"
            ],
            "x-enum-comments": {
                "UpToDate": "nothing to do",
                "UpdateAvailable": "soft nudge — allow access",
                "UpdateRequired": "force update — block access"
            },
            "x-enum-varnames": [
                "UpdateRequired",
                "UpdateAvailable",
                "UpToDate"
            ]
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_appversion_service.VersionCheckResponse": {
            "type": "object",
            "properties": {
                "clientVersion": {
                    "type": "string"
                },
                "currentVersion": {
                    "type": "string"
                },
                "forceUpdate": {
                    "type": "boolean"
                },
                "minVersion": {
                    "type": "string"
                },
                "releaseNotes": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_appversion_service.UpdateStatus"
                },
                "storeUrl": {
                    "type": "string"
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_auth_dto.Enable2FAResponse": {
            "type": "object",
            "properties": {
                "backupCodes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "qrCodeUrl": {
                    "type": "string"
                },
                "secret": {
                    "type": "string"
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_auth_dto.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_auth_dto.LoginResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "expiresIn": {
                    "description": "seconds",
                    "type": "integer"
                },
                "refreshToken": {
                    "type": "string"
                },
                "tokenType": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_auth_dto.UserPayload"
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_auth_dto.RefreshRequest": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_auth_dto.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "firstName",
                "lastName",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "username": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 3
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_auth_dto.UserPayload": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_auth_dto.Verify2FARequest": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_mobile_entity.UserMobile": {
            "type": "object",
            "properties": {
                "countryCode": {
                    "description": "e.g. \"+1\"",
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "e164": {
                    "description": "canonical form e.g. \"+15551234567\"",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isPrimary": {
                    "type": "boolean"
                },
                "isVerified": {
                    "type": "boolean"
                },
                "number": {
                    "description": "local number without country code",
                    "type": "string"
                },
                "tenantId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                },
                "verifiedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_notification_dto.TestEmailRequest": {
            "type": "object",
            "required": [
                "to"
            ],
            "properties": {
                "to": {
                    "type": "string"
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_notification_dto.TestEmailResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "sent": {
                    "type": "boolean"
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_passkey_dto.FinishLoginRequest": {
            "type": "object",
            "required": [
                "response",
                "sessionToken"
            ],
            "properties": {
                "response": {
                    "description": "raw AuthenticatorAssertionResponse JSON"
                },
                "sessionToken": {
                    "type": "string"
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_passkey_dto.FinishRegistrationRequest": {
            "type": "object",
            "required": [
                "friendlyName",
                "response",
                "sessionToken"
            ],
            "properties": {
                "friendlyName": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "response": {
                    "description": "raw AuthenticatorAttestationResponse JSON"
                },
                "sessionToken": {
                    "type": "string"
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_passkey_dto.PasskeyResponse": {
            "type": "object",
            "properties": {
                "attachment": {
                    "type": "string"
                },
                "backedUp": {
                    "type": "boolean"
                },
                "createdAt": {
                    "type": "string"
                },
                "friendlyName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isBiometric": {
                    "type": "boolean"
                },
                "lastUsedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_role_dto.RoleResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_role_entity.RoleSlug"
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_role_entity.RoleSlug": {
            "type": "string",
            "enum": [
                "admin",
                "user",
                "member"
            ],
            "x-enum-varnames": [
                "RoleAdmin",
                "RoleUser",
                "RoleMember"
            ]
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_user_dto.BlockUserRequest": {
            "type": "object",
            "required": [
                "reason"
            ],
            "properties": {
                "reason": {
                    "type": "string",
                    "minLength": 5
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_user_dto.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "newPassword",
                "oldPassword"
            ],
            "properties": {
                "newPassword": {
                    "type": "string",
                    "minLength": 8
                },
                "oldPassword": {
                    "type": "string"
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_user_dto.CreateUserRequest": {
            "type": "object",
            "required": [
                "email",
                "firstName",
                "lastName",
                "password",
                "roleId",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "lastName": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "phoneNumber": {
                    "type": "string"
                },
                "roleId": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 3
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_user_dto.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "firstName": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "gender": {
                    "type": "string",
                    "enum": [
                        "male",
                        "female",
                        "other"
                    ]
                },
                "lastName": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "phoneNumber": {
                    "type": "string"
                },
                "profilePicture": {
                    "type": "string"
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_user_dto.UserListResponse": {
            "type": "object",
            "properties": {
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_modules_user_dto.UserResponse"
                    }
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_modules_user_dto.UserResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "emailVerified": {
                    "type": "boolean"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastLoginAt": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "profilePicture": {
                    "type": "string"
                },
                "roleId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "twoFAEnabled": {
                    "type": "boolean"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorDetail": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorEnvelope": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_breadgarlicbigint_bread-golang-boilerplate_shared_response.ErrorDetail"
                    }
                },
                "message": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "requestId": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Bread Golang Boilerplate",
	Description:      "Production-ready Go REST API — JWT, RBAC, MongoDB, Redis, WebAuthn, FCM.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
